SERVER_PORT: 8080

POSTGRES_USER: user
POSTGRES_PASSWORD: password
POSTGRES_DB: todo_db
POSTGRES_PORT: 5432
POSTGRES_HOST: db

MIGRATIONS_PATH: file://db/migrations

JWT_TOKEN_LIFESPAN: 24h
JWT_SIGNATURE: my_secret_key

AUTH_REDIS_HOST: auth_redis
AUTH_REDIS_PORT: 6380
AUTH_REDIS_PASSWORD: password
AUTH_REDIS_DB: 0