services:
  todo-app:
    build: .
    container_name: todo_app
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - todo-network
    environment:
      SERVER_PORT: ${SERVER_PORT:-8080}
      JWT_SIGNATURE: ${JWT_SIGNATURE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      MIGRATIONS_PATH: ${MIGRATIONS_PATH}
      JWT_TOKEN_LIFESPAN: ${JWT_TOKEN_LIFESPAN}
      AUTH_REDIS_HOST: ${AUTH_REDIS_HOST}
      AUTH_REDIS_PORT: ${AUTH_REDIS_PORT}
      AUTH_REDIS_PASSWORD: ${AUTH_REDIS_PASSWORD}
      AUTH_REDIS_DB: ${AUTH_REDIS_DB}
    command: sh -c "./migrate && ./main"

  db:
    image: postgres:15-alpine
    container_name: todo_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:${POSTGRES_PORT}"
    volumes:
      - todo_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - todo-network
  
  auth_redis:
    image: redis:alpine
    command: redis-server --bind 0.0.0.0 --port ${AUTH_REDIS_PORT} --requirepass ${AUTH_REDIS_PASSWORD}
    ports:
      - "${AUTH_REDIS_PORT}:${AUTH_REDIS_PORT}"
    volumes:
      - auth_redis_data:/data
    environment:
      REDIS_PASSWORD: ${AUTH_REDIS_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -h localhost -p ${AUTH_REDIS_PORT} -a ${AUTH_REDIS_PASSWORD} ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  todo_data:
  auth_redis_data: